# Generated by Django 6.0.1 on 2026-05-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyapplication',
            name='tech',
            field=models.CharField(blank=True, db_column='tech', default='', help_text='Legacy technology field for compatibility', max_length=200, null=True),
        ),
    ]
